version: 0.0
os: linux

files:
  - source: /appspec.yml
    destination: /opt/codedeploy-agent/deployment-root/144a822c-cc4e-47d3-bfb9-31cd5cf28adc/d-SWU5NKR91/deployment-archive/
file_exists_behaviour: OVERWRITE

hooks:  
  BeforeInstall:
    - location: scripts/server_clear.sh
      timeout: 300
      runas: root 
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 3600
      runas: root
