version: 0.0
os: linux

files:
  - source: /my-app/*
    destination: /home/ubuntu/apache-tomcat-10.1.14/webapps

file_exists_behaviour: OVERWRITE

hooks:  
  ApplicationStop:
    - location: server_stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: server_start.sh
      timeout: 3600
      runas: root
