version: 0.2

env:
  variables:
    RUNTIME_VERSION: "16"  # Replace with the desired Node.js version

phases:
  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - echo "Build completed on `date`"
      - cp myreactapp /var/www/html/ 

artifacts:
  files: 
    - '**/*'
  base-directory: 'build'

cache:
  paths:
    - 'node_modules/**/*'

